### ISSUE TITLE
Black fill when referencing element

### ISSUE THREAD

**Issue by Ionaru** [dnfield/flutter_svg#634]
Issue split off from https://github.com/dnfield/flutter_svg/issues/630.

**Description**
When using `<use>` to reference a defined element (tested `<path>` and `<circle>`), the `fill="none"` attribute does not seem to be parsed correctly and a black fill is displayed instead. Any fill other than `none` does display correctly.

**SVG code**
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200">
   <defs>
      <path id="block-outline" fill="none" stroke="red" d="M50,50 h100 v100 h-100 z" />
   </defs>
   <use href="#block-outline" />
</svg>
```

**Expected result (Chrome)**
![image](https://user-images.githubusercontent.com/3472373/147024796-e523bc7b-c0ee-403b-8f8f-5d8d9eadcac1.png)

**Actual result (Flutter)**, ignore image size differences.
![image](https://user-images.githubusercontent.com/3472373/147024813-28c97470-7d3c-4a82-8cda-6866486f82ee.png)

**Version info**
- flutter_svg 1.0.0
- Flutter 2.8.0
- Dart 2.15.0
- Chrome 96
- Windows 10

**Additional info**

Maybe related to https://github.com/dnfield/flutter_svg/issues/64

**Comment by dnfield** [comment]
Fixed in 5ad8acc1530a0a35d264e81b9e36f8b0ad0f21bf

**Comment by dnfield** [comment]
Sorry, should have been c482b3ffdc0833d671de42ebc520d291648b1e28

**Comment by Mage111** [comment]
I'm still getting this effect in the latest flutter_svg package: 2.0.9
