### ISSUE TITLE
SVG Rendering Issue 

### ISSUE THREAD

**Issue by foxmedo** [dnfield/flutter_svg#755]
We are facing same issue, we are working on flutter 2.5.3 and in mobile some SVG are not rendered correctly.

This issue is happening with some SVG only we have other svg file which work perfectly 

**How SVG looks in the mobile phone**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/6687398/187028226-bb7be2f7-2712-4c9b-be19-76ce60622db9.png">

**The SVG file**
![order](https://user-images.githubusercontent.com/6687398/187028192-66051778-fefd-4fbb-8bfb-acbb65d2e7c5.svg)

Any idea how can we resolve this issue ?

**Comment by ikbendewilliam** [comment]
The issue are the pattern tags, for more information see #289

**Comment by foxmedo** [comment]
thank you for your comment,  pat i guess pattern tags issue has been resolved in previous version.

Dear @dnfield can you get a look on this please, we do not know what is the real cause of this rendering issue ?

**Comment by dnfield** [comment]
No, pattern tags are still not supported in flutter_svg - but are now supported in package:vector_graphics.

It's becoming more and more likely that I will make a new major revision of flutter_svg that just uses vector_graphics underneath...

**Comment by dnfield** [comment]
Duplicate of #289
