### ISSUE TITLE
Purple boxes appear inside the images when use Impeller

### ISSUE THREAD

**Issue by Abdelazeem777** [dnfield/flutter_svg#914]
When I enable Impeller render engine in ios, the images appear with some purples boxes inside them like the following:

<img width="277" alt="Screenshot 2023-04-27 at 11 18 42 PM" src="https://user-images.githubusercontent.com/30933932/234994717-d2612951-a9ad-4cdf-be16-b7e7eb469b37.png">
<img width="326" alt="Screenshot 2023-04-27 at 11 18 50 PM" src="https://user-images.githubusercontent.com/30933932/234994724-a9e858d1-7600-4080-9a3d-9fe74c6ac408.png">
<img width="301" alt="Screenshot 2023-04-27 at 11 18 57 PM" src="https://user-images.githubusercontent.com/30933932/234994740-45366498-715b-44f8-a44f-04da1ac8374f.png">

the original (Skia) engine:

<img width="320" alt="Screenshot 2023-04-27 at 11 31 28 PM" src="https://user-images.githubusercontent.com/30933932/234995847-edcc6bb1-cb82-4452-88fe-328856ef3263.png">
<img width="299" alt="Screenshot 2023-04-27 at 11 31 33 PM" src="https://user-images.githubusercontent.com/30933932/234995857-ef7d6d7c-9ca0-45d4-a8a3-c578bfc3c031.png">
<img width="285" alt="Screenshot 2023-04-27 at 11 31 39 PM" src="https://user-images.githubusercontent.com/30933932/234995865-4dd6d185-15b8-4975-b129-35189b76e455.png">

And there are no errors or crashes in debugging logs happen.

Flutter: v3.7.12

**Comment by dnfield** [comment]
Please share some SVGs that cause this - also if possible please confirm whether this happens on master (or at least beta). Many bugs in impeller have been fixed since the last stable.

**Comment by Abdelazeem777** [comment]
I checked the master and still have the same issue

here is an example:
![d6ae35783a544fe9b706b465eea2b592](https://user-images.githubusercontent.com/30933932/235346616-b7835c06-4547-4ae6-bc0a-2d0e9dd5f9cc.svg)

**Comment by dnfield** [comment]
I am not able to reproduce this on master.

**Comment by dnfield** [comment]
I'm not able to reproduce it on stable either... with the linked SVG.

**Comment by dnfield** [comment]
Perhaps you could provide a complete application reproduction? Sometimes using other options on the widget trigger things like color filtering that may affect this.

**Comment by dnfield** [comment]
In the mean time, I'm going to close this - but I will reopen if you provide a reproduction that works fo rme.

**Comment by Abdelazeem777** [comment]
I tried it on the package example and this how is it look:

![simulator_screenshot_DC2201E4-CE37-4D73-86C3-389225D3E7A9](https://user-images.githubusercontent.com/30933932/236625561-a0c41fba-cfea-4df3-885d-d1e41edf8fab.png)

Note.
Make sure that you add the Impeller tag at the end of `info.plist` file like this:
```xml
                 ...
		<key>FLTEnableImpeller</key>
		<true/>
	</dict>
</plist>
```

**Comment by dnfield** [comment]
Again, I am not able to reproduce this on the latest commit in flutter/flutter - the SVG renders fine when using impeller on an iPhone. Maybe you could share a full git repo that reproduces it. I tried replacing it in the sampe project and do not get the behavior you are seeing.

**Comment by Abdelazeem777** [comment]
Here is the repo with the modified example 
[flutter_svg.zip](https://github.com/dnfield/flutter_svg/files/11415612/flutter_svg.zip)

**Comment by dnfield** [comment]
I'm still not able to reproduce this on recent commits in flutter, and based on some of the other renderings in your screenshot I'm seeing other impeller-related bugs that have been fixed since the last stable release...

**Comment by Abdelazeem777** [comment]
On the master branch

Flutter v3.7.12
1. Simulator => Still face this issue
2. Real device => Still face this issue

Flutter v3.10.1
1. Simulator => Still face this issue
2. Real device => The issue disappeared

**Comment by MayurPoptaniSalt** [comment]
I also have a similar issue. 
Has anyone found a fix for it?
I am on Flutter 3.13.9 Stable with flutter_svg version 2.0.9
 
<img width="398" alt="Screenshot 2023-11-21 at 4 06 36 PM" src="https://github.com/dnfield/flutter_svg/assets/111430651/de3940e5-8c8b-4c25-aec2-fd5482f543f8">

**Comment by dnfield** [comment]
> I also have a similar issue. Has anyone found a fix for it? I am on Flutter 3.13.9 Stable with flutter_svg version 2.0.9
> 
> <img alt="Screenshot 2023-11-21 at 4 06 36 PM" width="398" src="https://user-images.githubusercontent.com/111430651/284548392-de3940e5-8c8b-4c25-aec2-fd5482f543f8.png">

Can you share the SVG? Does this happen on 3.16?
